### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by Blueflier** [joaquinllenado/Sneakr.#11]
Host it for free on:

- railway
- vercel
- aws
- netlify (my preference)

lmk if you need help :)

**Comment by joaquinllenado** [comment]
Hey Joseph, thank you for the suggestions! 

I actually ended up using vercel to host it, but I'll definitely look into using the others for my next projects. Here's the link if you're interested in checking it out: https://sneakr.vercel.app/ . 

I hope things have been going well, we definitely need to catch up soon!
